module.exports = {
	CommandTypes: {
		'SUB_COMMAND': 1,
		'SUB_COMMAND_GROUP': 2,
		'STRING': 3,
		'INTEGER': 4,
		'BOOLEAN': 5,
		'USER': 6,
		'CHANNEL': 7,
		'ROLE': 8,
		'MENTIONABLE': 9,
		'NUMBER': 10,
	},
	EventTypes: [
		'applicationCommandCreate',
		'applicationCommandDelete',
		'applicationCommandUpdate',
		'channelCreate',
		'channelDelete',
		'channelPinsUpdate',
		'channelUpdate',
		'debug',
		'emojiCreate',
		'emojiDelete',
		'emojiUpdate',
		'error',
		'guildBanAdd',
		'guildBanRemove',
		'guildCreate',
		'guildDelete',
		'guildIntegrationsUpdate',
		'guildMemberAdd',
		'guildMemberAvailable',
		'guildMemberRemove',
		'guildMembersChunk',
		'guildMemberUpdate',
		'guildUnavailable',
		'guildUpdate',
		'interaction',
		'interactionCreate',
		'invalidated',
		'invalidRequestWarning',
		'inviteCreate',
		'inviteDelete',
		'message',
		'messageCreate',
		'messageDelete',
		'messageDeleteBulk',
		'messageReactionAdd',
		'messageReactionRemove',
		'messageReactionRemoveAll',
		'messageReactionRemoveEmoji',
		'messageUpdate',
		'presenceUpdate',
		'rateLimit',
		'ready',
		'roleCreate',
		'roleDelete',
		'roleUpdate',
		'shardDisconnect',
		'shardError',
		'shardReady',
		'shardReconnecting',
		'shardResume',
		'stageInstanceCreate',
		'stageInstanceDelete',
		'stageInstanceUpdate',
		'stickerCreate',
		'stickerDelete',
		'stickerUpdate',
		'threadCreate',
		'threadDelete',
		'threadListSync',
		'threadMembersUpdate',
		'threadMemberUpdate',
		'threadUpdate',
		'typingStart',
		'userUpdate',
		'voiceStateUpdate',
		'warn',
		'webhookUpdate',
	],
	Permissions: [
		'CREATE_INSTANT_INVITE',
		'KICK_MEMBERS', 
		'BAN_MEMBERS',
		'ADMINISTRATOR',
		'MANAGE_CHANNELS', 
		'MANAGE_GUILD', 
		'ADD_REACTIONS',
		'VIEW_AUDIT_LOG',
		'PRIORITY_SPEAKER',
		'STREAM',	
		'VIEW_CHANNEL',
		'SEND_MESSAGES',
		'SEND_TTS_MESSAGES',	
		'MANAGE_MESSAGES',
		'EMBED_LINKS',
		'ATTACH_FILES',
		'READ_MESSAGE_HISTORY',
		'MENTION_EVERYONE',
		'USE_EXTERNAL_EMOJIS',
		'VIEW_GUILD_INSIGHTS',	
		'CONNECT',
		'SPEAK',
		'MUTE_MEMBERS',
		'DEAFEN_MEMBERS',
		'MOVE_MEMBERS',
		'USE_VAD',
		'CHANGE_NICKNAME',
		'MANAGE_NICKNAMES',	
		'MANAGE_ROLES',
		'MANAGE_WEBHOOKS',
		'MANAGE_EMOJIS_AND_STICKERS',
		'USE_APPLICATION_COMMANDS',
		'REQUEST_TO_SPEAK',
		'MANAGE_THREADS',
		'USE_PUBLIC_THREADS',
		'USE_PRIVATE_THREADS',
		'USE_EXTERNAL_STICKERS'
	]
}