/* eslint-disable no-useless-escape */
module.exports = {
	KONAMI_DB_QA_REGEX: /https?:\/\/www\.db\.yugioh-card\.com\/yugiohdb\/faq_search\.action\?ope=5&fid=(\d+)/g,
	KONAMI_DB_CARD_REGEX: /https?:\/\/www\.db\.yugioh-card\.com\/yugiohdb\/(?:card_search|faq_search)\.action\?ope=[24]&cid=(\d+)/g,
	YGORG_DB_QA_REGEX: /https?:\/\/db\.ygorganization\.com\/qa#(\d+)/g,
	YGORG_DB_CARD_REGEX: /https?:\/\/db\.ygorganization\.com\/card#(\d+)/g,
	EDIT_TIMEOUT: 10,
	QueryTypes: {
		'r': 'ruling',
		'a': 'art',
		'd': 'date',
		'p': 'yugipedia',
		'$': 'price',
		'f': 'faq',
		'q': 'qna'
	},
	Languages: {
		'de': 'German',
		'en': 'English',
		'es': 'Spanish',
		'fr': 'French',
		'it': 'Italian',
		'ja': 'Japanese',
		'ko': 'Korean',
		'pt': 'Portuguese'
	},
	LanguageEmojis: {
		'de': '🇩🇪',
		'en': '🇬🇧',
		'es': '🇪🇸',
		'fr': '🇫🇷',
		'it': '🇮🇹',
		'ja': '🇯🇵',
		'ko': '🇰🇷',
		'pt': '🇵🇹'
	},
	CommandTypes: {
		'SUB_COMMAND': 1,
		'SUB_COMMAND_GROUP': 2,
		'STRING': 3,
		'INTEGER': 4,
		'BOOLEAN': 5,
		'USER': 6,
		'CHANNEL': 7,
		'ROLE': 8,
		'MENTIONABLE': 9,
		'NUMBER': 10,
	},
	ChannelTypes: {
		'GUILD_TEXT': 0,
		'DM': 1,
		'GUILD_VOICE': 2,
		'GROUP_DM': 3,
		'GUILD_CATEGORY': 4,
		'GUILD_NEWS': 5,
		'GUILD_STORE': 6,
		'GUILD_NEWS_THREAD': 10,
		'GUILD_PUBLIC_THREAD': 11,
		'GUILD_PRIVATE_THREAD': 12,
		'GUILD_STAGE_VOICE': 13
	},
	EventTypes: [
		'applicationCommandCreate',
		'applicationCommandDelete',
		'applicationCommandUpdate',
		'channelCreate',
		'channelDelete',
		'channelPinsUpdate',
		'channelUpdate',
		'debug',
		'emojiCreate',
		'emojiDelete',
		'emojiUpdate',
		'error',
		'guildBanAdd',
		'guildBanRemove',
		'guildCreate',
		'guildDelete',
		'guildIntegrationsUpdate',
		'guildMemberAdd',
		'guildMemberAvailable',
		'guildMemberRemove',
		'guildMembersChunk',
		'guildMemberUpdate',
		'guildUnavailable',
		'guildUpdate',
		'interaction',
		'interactionCreate',
		'invalidated',
		'invalidRequestWarning',
		'inviteCreate',
		'inviteDelete',
		'message',
		'messageCreate',
		'messageDelete',
		'messageDeleteBulk',
		'messageReactionAdd',
		'messageReactionRemove',
		'messageReactionRemoveAll',
		'messageReactionRemoveEmoji',
		'messageUpdate',
		'presenceUpdate',
		'rateLimit',
		'ready',
		'roleCreate',
		'roleDelete',
		'roleUpdate',
		'shardDisconnect',
		'shardError',
		'shardReady',
		'shardReconnecting',
		'shardResume',
		'stageInstanceCreate',
		'stageInstanceDelete',
		'stageInstanceUpdate',
		'stickerCreate',
		'stickerDelete',
		'stickerUpdate',
		'threadCreate',
		'threadDelete',
		'threadListSync',
		'threadMembersUpdate',
		'threadMemberUpdate',
		'threadUpdate',
		'typingStart',
		'userUpdate',
		'voiceStateUpdate',
		'warn',
		'webhookUpdate',
	],
	Permissions: [
		'CREATE_INSTANT_INVITE',
		'KICK_MEMBERS', 
		'BAN_MEMBERS',
		'ADMINISTRATOR',
		'MANAGE_CHANNELS', 
		'MANAGE_GUILD', 
		'ADD_REACTIONS',
		'VIEW_AUDIT_LOG',
		'PRIORITY_SPEAKER',
		'STREAM',	
		'VIEW_CHANNEL',
		'SEND_MESSAGES',
		'SEND_TTS_MESSAGES',	
		'MANAGE_MESSAGES',
		'EMBED_LINKS',
		'ATTACH_FILES',
		'READ_MESSAGE_HISTORY',
		'MENTION_EVERYONE',
		'USE_EXTERNAL_EMOJIS',
		'VIEW_GUILD_INSIGHTS',	
		'CONNECT',
		'SPEAK',
		'MUTE_MEMBERS',
		'DEAFEN_MEMBERS',
		'MOVE_MEMBERS',
		'USE_VAD',
		'CHANGE_NICKNAME',
		'MANAGE_NICKNAMES',	
		'MANAGE_ROLES',
		'MANAGE_WEBHOOKS',
		'MANAGE_EMOJIS_AND_STICKERS',
		'USE_APPLICATION_COMMANDS',
		'REQUEST_TO_SPEAK',
		'MANAGE_THREADS',
		'USE_PUBLIC_THREADS',
		'USE_PRIVATE_THREADS',
		'USE_EXTERNAL_STICKERS'
	]
}